version: "3"
services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    platform: linux/amd64
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/tmp/hls
